[classes]
application = "BuerliDemoApp"
system  = "./cclasses/Source;System;Common.*;BaseModeling.*;CAD;Sheet;"

[classes.user]
tests   = "./cclasses/Source/Tests;*;"

[common]
tessellatecurves = 0
cc_productrefcreation = 3
datapath = "./data"

; Verbose
verbosefilename = "/Users/dev/dev/awv/classcad-ai/workspace/training/2026-09-16_12-50-53_pvs-cavity-boolean/files/worker.log"
verboselevel = 16583 ; 16455, 16583, 524288, 1047551, 1048575, 71, 99, 66(TDM)
loglevel = "debug"

; Testing
testinputpath = "./data/Test/Input"
testoutputpath = "./data/Test/Output"

; ShowClasses enables the developer mode
showclasses = 1

[smlib]
servicedll = "SMLibService_9.x;SMLibExpressService_9.x;BrepSimplificationService_9.x;ECXMLService;JWTService;GenericService;LGSService;LGS3DService;IDEConnectionService;RapidXmlService;NetworkService;TestService;DxfService;CryptoRtService;CryptoDevService"
servicedlld = "SMLibService_9.xd;SMLibExpressService_9.xd;BrepSimplificationService_9.xd;ECXMLServiced;JWTServiced;GenericServiced;LGSServiced;LGS3DServiced;IDEConnectionServiced;RapidXmlServiced;NetworkServiced;TestServiced;DxfServiced;CryptoRtServiced;CryptoDevServiced"
; servicedll = "SMLibService_9.x;SMLibExpressService_9.x;BrepSimplificationService_9.x;ECXMLService;JWTService;GenericService;LGSService;LGS3DService;IDEConnectionService;RapidXmlService;NetworkService;TestService;DxfService;CryptoRtService;CryptoDevService"
; servicedlld = "SMLibService_9.xd;SMLibExpressService_9.xd;BrepSimplificationService_9.xd;ECXMLServiced;JWTServiced;GenericServiced;LGSServiced;LGS3DServiced;IDEConnectionServiced;RapidXmlServiced;NetworkServiced;TestServiced;DxfServiced;CryptoRtServiced;CryptoDevServiced"

[network]
host = "0.0.0.0"
wport = 19094
hport = 19094
; webhook_auth = "http://localhost:3000/auth"
; webhook_state = "http://localhost:3000/state"

[network.ssl] ; this section is optional!
crtfile = "./ssl/selfsigned.awv.crt"
keyfile = "./ssl/selfsigned.awv.key"
wport = 19095
hport = 19095

[json]
tesselategraphicasync = 0 ; experimental

; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; ;;; generic app like developer ;;;;;;
; [json]
; filterconfig = "(APP_DIR)/filterconfig-all.json"
; transformtolocal = 0
; ;;; generic app like developer ;;;;;;
; ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
