// Bundle docs/*.md into dist/docs.js so every consumer — browser (buerli-ai),
// Node (mcp, harness) — can import the data contract without filesystem access:
//   import { docs } from '@classcad/script/docs'
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const docsDir = join(root, 'docs')
const outDir = join(root, 'dist')
mkdirSync(outDir, { recursive: true })

const entries = readdirSync(docsDir)
  .filter(f => f.endsWith('.md'))
  .map(f => [f.replace(/\.md$/, ''), readFileSync(join(docsDir, f), 'utf8')])
if (entries.length === 0) throw new Error(`No docs found in ${docsDir}`)

const body = `// Generated by scripts/build-docs.mjs — do not edit. Sources: docs/*.md\n` +
  `export const docs = ${JSON.stringify(Object.fromEntries(entries), null, 2)};\n` +
  `export default docs;\n`
writeFileSync(join(outDir, 'docs.js'), body)
writeFileSync(
  join(outDir, 'docs.d.ts'),
  `/** The @classcad/script data-contract documents (${entries.map(e => e[0]).join(', ')}), markdown text keyed by name. */\n` +
    `export declare const docs: Record<string, string>;\nexport default docs;\n`,
)
console.log(`[build-docs] ${entries.map(e => e[0]).join(', ')} → dist/docs.js`)
