// ─── Method registry — static metadata for all ClassCAD v1 API methods ────────
//
// The registry maps "v1.<domain>.<method>" to { domain, method, summary, params }.
// It can be loaded from:
//   1. A pre-built JSON bundle (shipped with this package or generated by build:skill)
//   2. Supplied by the consumer at runtime via setMethodRegistry()

export type RegistryEntry = {
  domain: string
  method: string
  summary: string
  params: Array<{ name: string; text: string }>
}

export type MethodRegistry = Record<string, RegistryEntry>

let registry: MethodRegistry | null = null

/** Set the method registry at runtime. Call this during app init. */
export function setMethodRegistry(r: MethodRegistry): void {
  registry = r
}

/** Get the current method registry (may be null if not loaded). */
export function getMethodRegistry(): MethodRegistry | null {
  return registry
}

let indexCache: { reg: MethodRegistry; text: string } | null = null

/** First sentence of a summary, collapsed and capped, for the compact index. */
function brief(summary: string): string {
  const s = (summary || '').replace(/\s+/g, ' ').trim()
  const dot = s.indexOf('. ')
  const f = dot > 0 && dot < 90 ? s.slice(0, dot + 1) : s
  return f.length > 90 ? f.slice(0, 88).trimEnd() + '…' : f
}

/**
 * A compact one-line-per-method index of every v1 method (`name: brief summary`),
 * built lazily from the registry and memoized. Injected into the system prompt so
 * the model can map intent → method directly instead of searching (~4.6k tokens for
 * the 254-method ClassCAD surface). Returns '' when the registry isn't loaded yet.
 */
export function getMethodIndex(): string {
  if (!registry) return ''
  if (indexCache && indexCache.reg === registry) return indexCache.text
  const text = Object.keys(registry)
    .sort()
    .map(k => `${k}: ${brief(registry![k].summary)}`)
    .join('\n')
  indexCache = { reg: registry, text }
  return text
}

/**
 * Load the registry from a JSON module.
 * Usage: `await loadMethodRegistry(import('./path/to/method-registry.json'))`
 */
export async function loadMethodRegistry(jsonModule: Promise<{ default: MethodRegistry }>): Promise<void> {
  const mod = await jsonModule
  registry = mod.default ?? (mod as any)
}
